// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv8FQq-Qu9Mlq-GBXmP-QduePFXrKVaDg',
    appId: '1:83695472584:web:d0d791d0465715530efafd',
    messagingSenderId: '83695472584',
    projectId: 'hyperbrew-fa370',
    authDomain: 'hyperbrew-fa370.firebaseapp.com',
    storageBucket: 'hyperbrew-fa370.firebasestorage.app',
    measurementId: 'G-WH8KGHZL1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMBsyl1xYaRRvvMaKBlE_IVujAd_YhmQ',
    appId: '1:83695472584:android:963fc8a7cb02397b0efafd',
    messagingSenderId: '83695472584',
    projectId: 'hyperbrew-fa370',
    storageBucket: 'hyperbrew-fa370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwc41GUZJO0-lpqJ3pDP4NMuUeWIbepM',
    appId: '1:83695472584:ios:ab6bf2fc362b48fb0efafd',
    messagingSenderId: '83695472584',
    projectId: 'hyperbrew-fa370',
    storageBucket: 'hyperbrew-fa370.firebasestorage.app',
    androidClientId: '83695472584-o809p1mlq5mgjund2m6d3vekckii74m3.apps.googleusercontent.com',
    iosClientId: '83695472584-bbjtkduglkbo359imim2sjh9cn8o4pmr.apps.googleusercontent.com',
    iosBundleId: 'pucminas.br.listApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTwc41GUZJO0-lpqJ3pDP4NMuUeWIbepM',
    appId: '1:83695472584:ios:bb6f785f1ed999e00efafd',
    messagingSenderId: '83695472584',
    projectId: 'hyperbrew-fa370',
    storageBucket: 'hyperbrew-fa370.firebasestorage.app',
    androidClientId: '83695472584-o809p1mlq5mgjund2m6d3vekckii74m3.apps.googleusercontent.com',
    iosClientId: '83695472584-2u89sqpg2arqkl1ni9eq502lv93s0v1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperbrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv8FQq-Qu9Mlq-GBXmP-QduePFXrKVaDg',
    appId: '1:83695472584:web:9ace496b7c2b94dc0efafd',
    messagingSenderId: '83695472584',
    projectId: 'hyperbrew-fa370',
    authDomain: 'hyperbrew-fa370.firebaseapp.com',
    storageBucket: 'hyperbrew-fa370.firebasestorage.app',
    measurementId: 'G-M3MVCNR4TN',
  );

}